### ISSUE TITLE
DocuWiki: Research on OpenSource Wiki

### ISSUE THREAD

**Issue by head-iie-vnr** [Vignana-Jyothi/web-ex#1]
Scope
- Download the source code
- Install the service. 
- Play with the Wiki page
- Explore unique capabiliites

Acceptance Criteria 
Write conclusion on what all funcitonalities can be used for College purpose.

**Comment by DEV-0912** [comment]
**// steps to install DocuWiki**
Starting a DokuWiki page on Linux is a great idea for documentation purposes. Here's a step-by-step guide to help you get started:

step 1. **Install Apache Web Server:**
   DokuWiki is a web-based application, so you'll need a web server. Apache is a popular choice. Install Apache using your distribution's package manager. For example, on Ubuntu or Debian:
   
   sudo apt update
   sudo apt install apache2
   

step 2. **Install PHP:**
   DokuWiki is written in PHP, so you need to install PHP and some necessary PHP extensions. Again, using apt:

   sudo apt install php php-cli php-mbstring php-gd php-xml php-ldap
  
step 3. **Install DokuWiki:**
   Download the latest version of DokuWiki from the official website or use `wget` directly on your Linux terminal:

  
   wget -O dokuwiki.tgz https://download.dokuwiki.org/src/dokuwiki/dokuwiki-stable.tgz


   Extract the downloaded archive:

  
   tar xzvf dokuwiki.tgz
   

   Move the extracted DokuWiki files to Apache's web root directory:

   
   sudo mv dokuwiki-*/ /var/www/html/dokuwiki
   

step 4. **Set Permissions:**
   Set appropriate permissions to DokuWiki's directory so that the web server can read and write files:

   
   sudo chown -R www-data:www-data /var/www/html/dokuwiki
   

5. **Configure Apache:**
   Create a new virtual host configuration file for DokuWiki:

   
   sudo nano /etc/apache2/sites-available/dokuwiki.conf
   `

   Add the following configuration:

   <VirtualHost *:80>
       ServerAdmin admin@example.com
       DocumentRoot /var/www/html/dokuwiki
       ServerName your_domain.com
       ServerAlias www.your_domain.com

       <Directory /var/www/html/dokuwiki>
           Options FollowSymLinks
           AllowOverride All
           Require all granted
       </Directory>

       ErrorLog ${APACHE_LOG_DIR}/error.log
       CustomLog ${APACHE_LOG_DIR}/access.log combined
   </VirtualHost>
   

   Enable the new virtual host and restart Apache:

   
   sudo a2ensite dokuwiki.conf
   sudo systemctl restart apache2
   

6. **Access DokuWiki:**
   Open your web browser and navigate to your server's IP address or domain name. You should see the DokuWiki installer page. Follow the on-screen instructions to complete the installation, including setting up an admin account and configuring basic settings.

**Comment by DEV-0912** [comment]
**when I open the page the index.php is getting rendered on the screen as text.   What could be the issue?**
  

**Solution**
677  sudo apt install libapache2-mod-php8.2
  678  sudo a2enmod php8.2
  679  sudo a2dismod php8.2
  680  sudo a2enmod php8.2
  681  sudo a2dismod mpm_event
  682  sudo a2enmod mpm_prefork
  683  sudo a2enmod php8.2

**Comment by DEV-0912** [comment]
****//CREATING NEW PAGE** 
SOLUTION** 
//REPLACE THE NEWPAGE WITH THE PAGE NAME YOU WANT TO ADD
http://10.45.34.199/doku.php?id=newpage

**Comment by DEV-0912** [comment]
![Screenshot from 2024-05-16 15-44-18](https://github.com/Vignana-Jyothi/web-ex/assets/169129783/6783376a-2e31-4ce1-8fc2-fcdc2df1c4a6)
**a sample page**

**Comment by DEV-0912** [comment]
![Screenshot from 2024-05-16 16-09-07](https://github.com/Vignana-Jyothi/web-ex/assets/169129783/c3cd8c07-7aaf-4143-947c-342d0c34abdc)
### if we add link of any youtube video we wont get thumbnail and controls of it

**Comment by DEV-0912** [comment]
![image](https://github.com/Vignana-Jyothi/web-ex/assets/169129783/081e9e6c-d66e-46ea-a6c7-a5c64b5a7935)
if we add any yt video its not working we are getting errors in it

**Comment by DEV-0912** [comment]
the plugins in dokuwiki are very old they are not working properly

**Comment by head-iie-vnr** [comment]
Thanks for doing this.
